config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "application#hello"
  get '/hello', to: 'application#hello'
  get '/venues/best_venues', to: 'venues#best', as: 'best_experiences'
  get '/current_user', to: 'users#get_current'
  get '/venues/:id/experiences', to: 'venues#collection'


  resources :categories, only: [:index, :new, :create, :show, :destroy] do
    resources :experiences, only: [:index]
  end

  resources :experiences, only: [:create, :update]
  resources :venues, only: [:new, :create, :edit, :update, :destroy]
  resources :venues, only: [:show] do
    resources :experiences
  end

  resources :experiences, only:[:show] do
  resources :user_comments, only: [:index, :new, :create, :edit, :update, :destroy]
end


  resources :user_experiences, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :locations, only: [:new, :create, :show]

end

app/models/experience.rb
class Experience < ApplicationRecord

  belongs_to :venue
  has_many :experience_categories
  has_many :categories, through: :experience_categories

  has_many :user_experiences, dependent: :destroy
  has_many :users, through: :user_experiences

  has_many :user_comments, dependent: :destroy
  has_many :comments, through: :user_comments


  validates :title, presence: true
  validates :title, uniqueness: true

    def venue_name=(name)
      self.venue = Venue.find_or_create_by(name: name)
    end

    def venue_name
      if self.venue
        self.venue
      end
    end

    def categories_attributes=(attributes_hash)
  if attributes_hash["0"]["name"].strip != ""
    attributes_hash.values.each do |attribute|
      category = Category.find_or_create_by(attribute)
      self.categories << category
    end
  end
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :user_experiences, dependent: :destroy
  has_many :experiences, through: :user_experiences

  has_many :user_comments, dependent: :destroy
  has_many :comments, through: :user_comments

  def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       user.provider = auth.provider
       user.uid = auth.uid
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
     end
   end

  def username
    self.email.split("@")[0]
  end

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  def index
    if params[:category_id]
      category = Category.find(params[:category_id])
      render json: category.experiences
    end
  end

  def new
    @experience = Experience.new(venue_id: params[:venue_id])
  end

  def create
    @venue = Venue.find_by(id: params[:experience][:venue_id])
    @experience = @venue.experiences.build(experience_params)
    if @experience.save
      redirect_to venue_experience_path(@venue, @experience)
    else
      render :new
    end
  end

  def show
    if params[:venue_id]
      venue_variable
      experience_variable
      if user_signed_in?
        @comments = UserComment.new(experience_id: @experience.id, user_id: current_user.id)
      end
    end
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @experience }
    end
  end

  def edit
    if params[:venue_id]
      venue_variable
      experience_variable
    else
      @experience = Experience.find(params[:id])
    end
  end

  def update
    @venue = Venue.find_by(id: params[:experience][:venue_id])
    @experience = @venue.experiences.find_by(id: params[:id])
    if @experience.update(experience_params)
      redirect_to venue_experience_path(@venue, @experience)
    else
      render :edit
    end
  end

  def destroy
    venue_variable
    experience_variable
    @experience.destroy
    redirect_to venue_path(@venue)
  end

  private
    def experience_params
      params.require(:experience).permit(:title, :genre, :description, :venue_id, category_ids:[], categories_attributes: [:name])
    end

    def venue_variable
      @venue = Venue.find_by(id: params[:venue_id])
    end

    def experience_variable
      @experience = venue_variable.experiences.find_by(id: params[:id])
    end


end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_form.html.erb
<%= form_for experience do |f| %>
  <%= f.hidden_field :venue_id %>

  <div class:"fields_with_errors" id="errors" >
    <% if @experience.errors.any? %>
      <ul>
        <% @experience.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
  <div class:"fields_with_errors">

  <div class="field">
    <%= f.label :title, 'Title:' %><br>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= f.label :genre, 'Genre:' %><br>
    <%= f.text_field :genre %>
  </div>

  <br>
  <div class="field">
    <%= f.label :description, 'Inside scoop(description):' %><br>
    <%= f.text_field :description %>
  </div>
<br>

<div class="field">
  Select Categories:<br>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
</div>
<br>

<div class="field">
  Add a Category:<br>
  <%= f.fields_for :categories, experience.categories.build do |categories_fields| %>
    <%= categories_fields.text_field :name %>
  <% end %>
</div>
<br>

  <div class="action">
    <%= f.submit 'Create Experience!' %>
  </div>
<% end %>

app/views/experiences/_signin.html.erb
<% if user_signed_in? %>
  <%= link_to "Edit Experience", edit_experience_path(experience) %> |
  <%= link_to "Remove Experience", experience_path(experience), method: "delete" %> |
  <%= link_to "Add Experience", new_experience_experience_path(experience) %><br><br>
<% end %>

app/views/experiences/edit.html.erb
<div class="show">
  <h2>Edit Experience:</h2>
</div>

<%= render partial: 'form', locals: {experience: @experience, venue: @venue} %>

app/views/experiences/show.html.erb
<div id="experience-ids" data-experience-ids="<%= @experience.venue.experience_ids %>"></div>
<a href="#" class="js-next" data-id="<%=@experience.id%>" data-venue="<%=@experience.venue.id%>">NEXT</a>

<% if user_signed_in? %>
  <div id="current-user" data-current-user="<%= { id: current_user.id, email: current_user.email }.to_json %>"></div>

  <div class="actions">
  <%= button_to 'Add Experience to Profile', user_experiences_path(experience_id: @experience) %>
  </div>
  <br>
  <div class="add">
    <%= link_to "Edit", edit_venue_experience_path(@experience.venue, @experience) %> |
    <%= link_to "Remove", venue_experience_path(@experience.venue, @experience), method: "delete" %>
  </div>
<% end %>

<div class="experience_show">
  <h2><%= @experience.title %></h2>
  <p id="artist"><strong>Genre:</strong> <%= @experience.genre %></p>
  <p id="description"><strong>Description:</strong> <%= @experience.description %></p>
</div>
<br>

<div class="categories_list">
    <strong>CATEGORIES:</strong>
    <% @experience.categories.each do |category| %>
    <%= link_to category.name, category_path(category) %> |
    <% end %>
</div>

<% if user_signed_in? %>
<div class="comments" id="<%=@experience.id%>" data-id="<%=@experience.venue.id%>">
  <h3>Leave your comments down below!</h3>
  <ul>
  </ul>
</div>

  <%= form_for ([@experience, @comments]) do |f| %>
    <%= render partial: 'user_comments/form', locals: {f: f} %>
  <% end %>
<br>
  <div class="rating" id="<%=@experience.id%>" data-id="<%=@experience.venue.id%>">
    <h3>Leave a rating</h3>

    <ul>
    </ul>
  </div>

<% end %>