config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "application#hello"
  get '/hello', to: 'application#hello'
  get '/venues/best_venues', to: 'venues#best', as: 'best_experiences'
  get '/current_user', to: 'users#get_current'
  get '/venues/:id/experiences', to: 'venues#collection'


  resources :categories, only: [:index, :new, :create, :show, :destroy] do
    resources :experiences, only: [:index]
  end

  resources :experiences, only: [:create, :update]
  resources :venues, only: [:new, :create, :edit, :update, :destroy]
  resources :venues, only: [:show] do
    resources :experiences
  end

  resources :experiences, only:[:show] do
  resources :user_comments, only: [:index, :new, :create, :edit, :update, :destroy]
end


  resources :user_experiences, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :locations, only: [:new, :create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.alphabetical
    order('name ASC')
  end
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :experience_categories
  has_many :experiences, through: :experience_categories
end

app/models/experience.rb
class Experience < ApplicationRecord

  belongs_to :venue
  has_many :experience_categories
  has_many :categories, through: :experience_categories

  has_many :user_experiences, dependent: :destroy
  has_many :users, through: :user_experiences

  has_many :user_comments, dependent: :destroy
  has_many :comments, through: :user_comments


  validates :title, presence: true
  validates :title, uniqueness: true

    def venue_name=(name)
      self.venue = Venue.find_or_create_by(name: name)
    end

    def venue_name
      if self.venue
        self.venue
      end
    end

    def categories_attributes=(attributes_hash)
  if attributes_hash["0"]["name"].strip != ""
    attributes_hash.values.each do |attribute|
      category = Category.find_or_create_by(attribute)
      self.categories << category
    end
  end
end

end

app/models/experience_category.rb
class ExperienceCategory < ApplicationRecord

  belongs_to :experience
  belongs_to :category 
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :venues, dependent: :destroy;

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :user_experiences, dependent: :destroy
  has_many :experiences, through: :user_experiences

  has_many :user_comments, dependent: :destroy
  has_many :comments, through: :user_comments

  def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       user.provider = auth.provider
       user.uid = auth.uid
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
     end
   end

  def username
    self.email.split("@")[0]
  end

end

app/models/user_comment.rb
class UserComment < ApplicationRecord
  belongs_to :user
  belongs_to :experience

  validates :comments, presence: true

  def username
    self.user.username
  end
end

app/models/user_experience.rb
class UserExperience < ApplicationRecord
  belongs_to :user
  belongs_to :experience

end

app/models/venue.rb
class Venue < ApplicationRecord

  has_many :experiences, dependent: :destroy
  belongs_to :location

  # validates :name, uniqueness: true
  validates :name, presence: true
  validates :rating, :numericality => { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

  def location_attributes=(attributes_hash)
    if attributes_hash["name"].strip != ""
      attributes_hash.values.each do |attribute|
        location = Location.find_or_create_by(name: attribute)
        self.location = location
      end
    end
  end

  def self.best_experiences
    joins(:experiences).group(:id).order("count(*) DESC").limit(3)
  end

  # def highest_rated
  #   .select("venues.id, avg(comments.rating) as average_rating, count(comments.id) as number_of_comments")
  #   joins(:venues).group("venues.id").order("average_rating DESC, number_of_comments DESC")
  # end
end


# @items = Item.where(:shop_name => @shop.name).joins(:reviews)
#   .select("items.id, avg(reviews.rating) as average_rating, count(reviews.id) as number_of_reviews")
#   .group("items.id")
#   .order("average_rating DESC, number_of_reviews DESC")

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
   @categories = Category.all
 end

 def new
   @category = Category.new
 end

 def create
   @category = Category.new(category_params)
   if @category.save
     redirect_to categories_path
   else
     render :new
   end
 end

 def show
   @category = Category.find(params[:id])
 end

 def destroy
   @category = Category.find(params[:id])
   @category.destroy
   redirect_to categories_path
 end

 private
   def category_params
     params.require(:category).permit(:name)
   end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def location_params
      params.require(:location).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
    end

    session[:user_id] = @user.id

    render 'application/hello'
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def get_current
    render json: current_user
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  before_action :venue_var, only: [:show, :edit, :update, :destroy, :collection]

    def new
      @venue = Venue.new
    end

    def create
      @venue = Venue.new(venue_params)
      if @venue.save
        redirect_to venue_path(@venue)
      else
        render :new
      end
    end

    def show
    end

    def edit
    end

    def update
      if @venue.update(venue_params)
        redirect_to venue_path(@venue)
      else
        render :edit
      end
    end

    def best
      @venues = Venue.best_experiences
    end

    def destroy
      @venue.destroy
      redirect_to root_path
    end

    def collection
      @experiences = @venue.experiences
      render json: @experiences
    end

    private
      def venue_params
        params.require(:venue).permit(:name, :description, :rating, :location_id, location_attributes: [:name])
      end
      def venue_var
        @venue = Venue.find(params[:id])
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

app/helpers/user_experiences_helper.rb
module UserExperiencesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/categories/_form.html.erb
<%= form_for category do |f| %>

<div class="fields_with_errors">
  <% if category.errors.any? %>
    <ul>
      <% category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
  <div class="fields_with_errors">

  <div class="field">
    <%= f.label :name, 'Category:' %><br>
    <%= f.text-field :name %>
  </div>
  <br>

  <div class="actions">
    <%= f.submit 'Add One of Your Own' %>
  </div>


<% end %>

app/views/categories/index.html.erb
<div class="add">
  <% if user_signed_in? %>
    <%= link_to "Add Category", new_category_path %>
  <% end %>
</div>

<div class="show">
  <h2>Categories</h2>
</div>

<div class="categories_list">
  <ul>
    <% @categories.alphabetical.each do |category| %>
      <li><%= category.name %></li>
    <% end %>
  </ul>
</div>

app/views/categories/new.html.erb
<h2>New Category:</h2>

<%= render partial: 'form', locals: {category: @category} %>

app/views/categories/show.html.erb
<div class="add">
  <% if user_signed_in? %>
    <%= link_to "Remove", category_path(@category), method: "delete" %>
  <% end %>
</div>

<div class="show">
  <h2><%= @category.name %></h2>
</div>

<div id="<%= @category.id %>" class="experience_list">
  <ul>
  </ul>
</div>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
  <div class:"fields_with_errors">
    <% if @location.errors.any? %>
      <ul>
        <% @location.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
  <div class:"fields_with_errors">

  <div class="field">
    <%= f.label :name, 'Location (ex. Brooklyn, New York):' %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="action">
    <%= f.submit 'Create Location' %>
  </div>
<% end %>

app/views/locations/new.html.erb
<h1> Hello, add your location: </h1>

<%= render partial: 'form', locals: {location: @location} %> 

app/views/users/show.html.erb
<div class="show">
  <h2><%= @user.username %>'s List of VR Experiences</h2>
</div>

<div class="experience_list">
  <ul>
    <% @user.user_experiences.each do |user_experience| %>
      <li>
        <% if user_experience%>
          <%= link_to "#{user_experience.experience.title}  |  #{user_experience.experience.genre} ", venue_experience_path(user_experience.experience.venue, user_experience.experience)%><br>
          <br><%= link_to "Remove", user_experience_path(user_experience), method: "delete", id: "remove" %><br>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/venues/_collection_signin.html.erb
<% if user_signed_in? %>
  | <%= link_to "Edit", edit_venue_experience_path(venue, experience) %>
  | <%= link_to "Remove", venue_experience_path(venue, experience), method: "delete" %>
<% end %>

app/views/venues/_form.html.erb
<%= form_for venue do |f| %>
  <div class:"fields_with_errors" id= "errors">
    <% if venue.errors.any? %>
      <ul>
        <% venue.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
  <div class:"fields_with_errors">

  <div class="field">
    <%= f.label :name, 'Name of Venue:' %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :description, 'Inside scoop:' %><br>
    <%= f.text_field :description %>
  </div>
  <br>

  <div class="field">
    <%= f.label :rating, 'Rating:' %><br>
    <%= f.text_field :rating %>
  </div>
  <br>

  <br/><br/>

  <div class="field">
    Choose a Location:
  <br>
    <%= f.collection_select :location_id, Location.all, :id, :name, include_blank: ""  %><br>
  </div>
  <br>
  <div class="field">
    Or Add One (ex. Dublin, Ireland):<br>
    <%= f.fields_for :location,venue.build_location do |locations_fields| %>
      <%= locations_fields.text_field :name %>
    <% end %>
  </div>
  <br>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/_ratings.html.erb
<form class="rating" method="GET" action="." target="new">
    <legend>Please rate:</legend>
    <input type="radio" class="star" id="star5" name="rating" value="5" /><label for="star5" title="Rocks!">5 stars</label>
    <input type="radio" class="star" id="star4" name="rating" value="4" /><label for="star4" title="Pretty good">4 stars</label>
    <input type="radio" class="star" id="star3" name="rating" value="3" /><label for="star3" title="Meh">3 stars</label>
    <input type="radio" class="star" id="star2" name="rating" value="2" /><label for="star2" title="Kinda bad">2 stars</label>
    <input type="radio" class="star" id="star1" name="rating" value="1" /><label for="star1" title="Sucks big time">1 star</label>

</form>
<br/>
<br/>

app/views/venues/_signin.html.erb
<% if user_signed_in? %>
  <%= link_to "Edit Venue", edit_venue_path(venue) %> |
  <%= link_to "Remove Venue", venue_path(venue), method: "delete" %> |
  <%= link_to "Add Experience", new_venue_experience_path(venue) %><br><br>
<% end %>

app/views/venues/best.html.erb
<div class="show">
  <h2>Best Venues</h2>
  <p>
    <% @venues.each do |venue| %>
      <%= link_to venue.name, venue_path(venue) %><br>
      <%= pluralize(venue.experiences.count, "experience")%><br>
      Rating: <%= venue.rating %> <%= pluralize(venue.rating, 'Star').split(" ", 2)[1] %>
<br><br>
    <% end %>
  </p>
</div>

app/views/venues/edit.html.erb
<div class="show">
  <h2>Edit Venue:</h2>
</div>

<%= render partial: 'form', locals: {venue: @venue} %>

app/views/venues/new.html.erb
<h1> Add a Venue: </h1>

<%= render partial: 'form' %>

app/views/venues/show.html.erb
<div class="show">
  <h2><%= @venue.name %></h2>
  <p id="location">Location: <%= @venue.location.name %></p>
  <p>Description: <%= @venue.description %></p>
  <p>Rating: <%= @venue.rating %> <%= pluralize(@venue.rating, 'Star').split(" ", 2)[1] %></p>
</div>


<div class="add" id="add">
  <%= render partial: 'venues/signin', locals: {venue: @venue} %>
</div>
</br>
<div class="collection_list">
  <h3>Collection of Experiences</h3>
  <ul>
    <% @venue.experiences.each do |experience| %>
      <li>
        Title: <%= experience.title %></br>
        Genre: <%= experience.genre %>
        <br>

        <%= link_to "View", venue_experience_path(@venue, experience) %>
        <%= render partial: 'venues/collection_signin', locals: {venue: @venue, experience: experience} %>
      <br><br>
    </li>
    <% end %>
  </ul>
</div>