config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "application#hello"
  get '/hello', to: 'application#hello'
  get '/venues/best_venues', to: 'venues#best', as: 'best_experiences'
  get '/current_user', to: 'users#get_current'
  get '/venues/:id/experiences', to: 'venues#collection'


  resources :categories, only: [:index, :new, :create, :show, :destroy] do
    resources :experiences, only: [:index]
  end

  resources :experiences, only: [:create, :update]
  resources :venues, only: [:new, :create, :edit, :update, :destroy]
  resources :venues, only: [:show] do
    resources :experiences
  end

  resources :experiences, only:[:show] do
  resources :user_comments, only: [:index, :new, :create, :edit, :update, :destroy]
end


  resources :user_experiences, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :locations, only: [:new, :create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.alphabetical
    order('name ASC')
  end
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :experience_categories
  has_many :experiences, through: :experience_categories
end

app/models/experience.rb
class Experience < ApplicationRecord

  belongs_to :venue
  has_many :experience_categories
  has_many :categories, through: :experience_categories

  has_many :user_experiences, dependent: :destroy
  has_many :users, through: :user_experiences

  has_many :user_comments, dependent: :destroy
  has_many :comments, through: :user_comments


  validates :title, presence: true
  validates :title, uniqueness: true

    def venue_name=(name)
      self.venue = Venue.find_or_create_by(name: name)
    end

    def venue_name
      if self.venue
        self.venue
      end
    end

    def categories_attributes=(attributes_hash)
  if attributes_hash["0"]["name"].strip != ""
    attributes_hash.values.each do |attribute|
      category = Category.find_or_create_by(attribute)
      self.categories << category
    end
  end
end

end

app/models/experience_category.rb
class ExperienceCategory < ApplicationRecord

  belongs_to :experience
  belongs_to :category 
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :venues, dependent: :destroy;

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :user_experiences, dependent: :destroy
  has_many :experiences, through: :user_experiences

  has_many :user_comments, dependent: :destroy
  has_many :comments, through: :user_comments

  def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       user.provider = auth.provider
       user.uid = auth.uid
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
     end
   end

  def username
    self.email.split("@")[0]
  end

end

app/models/user_comment.rb
class UserComment < ApplicationRecord
  belongs_to :user
  belongs_to :experience

  validates :comments, presence: true

  def username
    self.user.username
  end
end

app/models/user_experience.rb
class UserExperience < ApplicationRecord
  belongs_to :user
  belongs_to :experience

end

app/models/venue.rb
class Venue < ApplicationRecord

  has_many :experiences, dependent: :destroy
  belongs_to :location

  # validates :name, uniqueness: true
  validates :name, presence: true
  validates :rating, :numericality => { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

  def location_attributes=(attributes_hash)
    if attributes_hash["name"].strip != ""
      attributes_hash.values.each do |attribute|
        location = Location.find_or_create_by(name: attribute)
        self.location = location
      end
    end
  end

  def self.best_experiences
    joins(:experiences).group(:id).order("count(*) DESC").limit(3)
  end

  # def highest_rated
  #   .select("venues.id, avg(comments.rating) as average_rating, count(comments.id) as number_of_comments")
  #   joins(:venues).group("venues.id").order("average_rating DESC, number_of_comments DESC")
  # end
end


# @items = Item.where(:shop_name => @shop.name).joins(:reviews)
#   .select("items.id, avg(reviews.rating) as average_rating, count(reviews.id) as number_of_reviews")
#   .group("items.id")
#   .order("average_rating DESC, number_of_reviews DESC")

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
    end

    session[:user_id] = @user.id

    render 'application/hello'
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def get_current
    render json: current_user
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  before_action :venue_var, only: [:show, :edit, :update, :destroy, :collection]

    def new
      @venue = Venue.new
    end

    def create
      @venue = Venue.new(venue_params)
      if @venue.save
        redirect_to venue_path(@venue)
      else
        render :new
      end
    end

    def show
    end

    def edit
    end

    def update
      if @venue.update(venue_params)
        redirect_to venue_path(@venue)
      else
        render :edit
      end
    end

    def best
      @venues = Venue.best_experiences
    end

    def destroy
      @venue.destroy
      redirect_to root_path
    end

    def collection
      @experiences = @venue.experiences
      render json: @experiences
    end

    private
      def venue_params
        params.require(:venue).permit(:name, :description, :rating, :location_id, location_attributes: [:name])
      end
      def venue_var
        @venue = Venue.find(params[:id])
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

app/helpers/user_experiences_helper.rb
module UserExperiencesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/_header.html.erb
<nav>
  <ul id="navigator-list">
    <h2 id="logo" class="type"></h2>
    <script type="text/javascript">
      var typed = new Typed(".type", {
        strings: [
          "VR Guide",
          "VR Experiences",
          "VR Venues",
          "VR Artshows"],
        typeSpeed: 90,
        backSpeed: 50,
        loop: true // Default value
      });

    </script>

    <li id="nav-links"><%= link_to "Home", root_path %> |
    <%= link_to "Best Venues", best_experiences_path %> |
    <%= render partial: 'layouts/signin' %></li>
  </ul>
</nav>

app/views/layouts/_signin.html.erb
<% if user_signed_in? %>
  Hello, <%= current_user.email %> |
  <%= link_to 'Profile', user_path(current_user) %> |
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign In', new_user_session_path %> |
  <%= link_to 'Sign Up', new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Virtual Reality World</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Jura:700" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>

  <body>
    <header>
        <%= render 'layouts/header' %>
    </header>


    <main class="content">
      <%= yield %>
    </main>

    <!-- Main javascript file -->
    <footer id="footer">
        Copyright (c) 2017 <a href="/"><strong>VR Guide</strong></a> All Rights Reserved.
      </footer>
  </body>
</html>